server:
  port: 8088
spring:
  redis:
#  redis第0个库
    database: 0
#    地址
    host: localhost
#    端口
    port: 6379
#    密码
    password: 123456
#    集群模式  如果需要，把host和port禁用，开启下面cluster.nodes即可
#    cluster:
#      nodes:
#      - 127.0.0.1:6379
#      - 127.0.0.1:6380
#      - 127.0.0.1:6381
#      - 127.0.0.1:6388
#   此处不适用jedis线程池，因为是非线程安全。如果出现多线程抢夺资源，redis串行操作数据异常。另外jedis连接数量过多，资源消耗阶梯式增大，连接成本就较高。
    lettuce:
      pool:
#      连接池最大连接数（使用负值表示没有限制）
        max-active: 8
#        连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#        连接池中的最大空闲连接
        max-idle: 8
#        连接池中的最小空闲连接
        min-idle: 0
#    连接超时时间（毫秒）
    timeout: 30000ms
